print('Введите координаты точки А:')
xa = float(input('X: '))
ya = float(input('Y: '))
print("Введите координаты точки B:")
xb = float(input('X: '))
yb = float(input('Y: '))
import math
sqrt = math.sqrt((xa - xb)**2 + (ya - yb)**2)
a=round(sqrt,3)
print('Расстояние между A и B: ',a)